### ISSUE TITLE
No Issue : Question 

### ISSUE THREAD

**Issue by zorglube** [tprelog/iocage-esphome#12]
Hello @tprelog, you've been very helpful for me when I worked on MovieNight TrueNAS plug-in, thank for that. 

You say you stopped using TrueNAS Core, ok. May I ask what you choose instead ? 

See ya 
Z.

**Comment by tprelog** [comment]
Hi @zorglube,  I've switched my server over to TrueNAS SCALE. Originally I was trying to learn about making SCALE apps but as it turns out, that's more complicated than what I can learn. For now, I'm using a startup script to enable docker and running containers setup with docker-compose, which is considered a hack and is NOT supported by TrueNAS. That said, it works flawlessly (at least for now)

**Comment by zorglube** [comment]
Does the switch was easy ? 
I TrueNAS Scale work like TrueNAS Core ? I mean, has an appliance on the side of the storage and Jail/Container. 

As far as I understood, TrueNAS Scale is based on Linux Debian l, am I right ?

**Comment by tprelog** [comment]
For me the switch was easy. I did it months ago during the ALPHA release, before there was a migration. (I don't know how the migration works because I didn't use it) -- My setup is very simple. I have two zpools, one for media served by Emby and another to hold data and jails/containers. Beyond that I only have 3 or 4 Samba shares because I mainly access my TrueNAS using ssh.

When I switch to SCALE I just did a clean install, imported my zpools and then setup my server from scratch. With my setup, this only took about 30 min from shutting down CORE till I was completely setup on SCALE (excluding apps)

As far as the NAS function it works just like TrueNAS CORE and yes, SCALE is also designed as appliance. Even the GUI is very similar. Some of the menus are arranged different but otherwise it basically the same. I had no trouble finding my way around in SCALE.

You are correct, TrueNAS SCALE is based on Debian (I use another Linux on my daily computer so I'm more familiar than FreeBSD) - I switched to SCALE because there was promise to run docker. Unfortunately it turns out they are using Kubernetes to run docker containers... Not exactly the same thing. I do understand Kubernetes it is a better choice for TrueNAS SCALE, especially enterprise customers, but I found Kubernetes far to complicated for my simple home use - After weeks of trying to learn Kubernetes, I barely had any understanding of how it works - On the other hand, I was able to learn enough docker to run apps in under one hour -- This is why I've taken the risk to just use docker (and docker-compose)

As far as using docker on SCALE instead of jails on CORE, for me it comes to support from the app itself. I'm running Home Assistant to power my smart home but Home Assistant does not support FreeBSD, so running in a jail does have some issues. Turns out, running Home Assistant in Kubernetes has its own challenges that I think make it even more complicated than using jail... but as I mentioned earlier, using docker-compose was simple and it just works. SCALE, Home Assistant and the other few apps I run are all running flawlessly.

Sadly I can not recommend my approach because _it is unsupported to use docker-compose on SCALE_ - But if you want to take the risk yourself, here is a link to my startup script that will enable docker

https://gist.github.com/tprelog/7988dc6b196775f33929beb19f0090d7

**Comment by zorglube** [comment]
Thank a lot for the explantations. 

I guess I'll stay on `TrueNAS Core` for the moment.

**Comment by zorglube** [comment]
Also I guess you'll stop maintaining the `TrueNAS` plugins you wrote ?

**Comment by tprelog** [comment]
> Also I guess you'll stop maintaining the `TrueNAS` plugins you wrote ?

At this point I intend to keep my plugins maintained for as long it's feasible.

ESPHome is an exception because it requires platform.io toolchains to be compiled from ports off github - I've managed to make another plugin that somewhat automates this but I'm in over my head. Basically it either works or it doesn't. When it works, great! When it doesn't, I have no idea what I'm doing or where to begin fixing things. And honestly, I just want to run some apps on my TrueNAS. It's one thing to write a bash script for basic installation, but I'm not trying to become a real developer and I have no time for learning the ins and outs of compiling software on FreeBSD.

**Comment by zorglube** [comment]
By maintaining the plugins, I meaned `maintaining the deployment/start/stop/update` note the plugin code by itself.

**Comment by tprelog** [comment]
>maintaining the deployment/start/stop/update

Yes, this is relatively easy for me to maintain and I will continue doing so for as long as I can


>not the plugin code by itself.

ESPHome _requires_ plugin code (the platform.io toolchains) to also be maintained. Even if the deployment/start/stop/update are all working correctly, ESPHome on FreeBSD is practically useless without the platform.io toolchains. That is why I mention ESPHome as an exception.

**Comment by zorglube** [comment]
Ok I understand better. 

That's the open-source life: **if no one needs it enough, their's no support**.
